#!/bin/bash

echo
echo "*************************************************"
echo "This script removes all old fixtures for new data in the db!"
echo "*************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
  exit 0
fi
echo

python3 manage.py dumpdata auth.User --indent 4 > fixtures/users.json
python3 manage.py dumpdata passwords.Password --indent 4 > fixtures/passwords.json
python3 manage.py dumpdata passwords.Subscriber --indent 4 > fixtures/subscribers.json
python3 manage.py dumpdata passwords.Settings --indent 4 > fixtures/settings.json
