#!/bin/bash

# echo "Activating virtual enviroment (venv) ..."
# source ~/venv/bin/activate
# if [ "$VIRTUAL_ENV" == "" ]; then
#   exit 1
# fi
# echo "Done"

echo "Syncing database ..."
python3 manage.py makemigrations
if [ ! $? -eq 0 ]; then
  exit 1
fi
python3 manage.py migrate
if [ ! $? -eq 0 ]; then
  exit 1
fi
echo "Done"

python3 manage.py runserver 0.0.0.0:8000
