# Generated by Django 2.2 on 2021-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='instant_unlock_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
