# Generated by Django 2.2 on 2021-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_password_instant_unlock_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='challenge_time',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
