# Generated by Django 2.2 on 2021-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_auto_20210309_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='instant_unlock_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
